/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Untitled.glb --instanceall 
Files: Untitled.glb [178.36KB] > E:\projects\spotium\Untitled-transformed.glb [7.48KB] (96%)
*/

import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = React.createContext()

export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/Untitled-transformed.glb')
  const instances = React.useMemo(
    () => ({
      Logoxx: nodes.logo_13x86x55,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.Logoxx position={[-5.81, 0, -26.42]} />
    </group>
  )
}

useGLTF.preload('/Untitled-transformed.glb')
